services:
  - type: web
    name: gethereemu-site
    runtime: static
    buildCommand: ""
    publishPath: "."
    headers:
      - path: "/*.mobileconfig"
        name: "Content-Type"
        value: "application/x-apple-aspen-config"
      - path: "/*.mobileconfig"
        name: "Content-Disposition"
        value: "attachment; filename=\"profil.mobileconfig\""
      - path: "/*.apk"
        name: "Content-Type"
        value: "application/vnd.android.package-archive"
